---
- hosts: localhost
  tasks:
  - name: Start VM based on Cloud init 
    ovirt: user=admin@internal url=https://rhevm2.coe.hst.sin2.redhat.com instance_name=web-server password=$!ng@p0r3 state=started
